//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:24:40 AM IST 
//


package com.example.review.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.review.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.review.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Feed }
     * 
     */
    public Feed createFeed() {
        return new Feed();
    }

    /**
     * Create an instance of {@link ReviewType }
     * 
     */
    public ReviewType createReviewType() {
        return new ReviewType();
    }

    /**
     * Create an instance of {@link AggregatorType }
     * 
     */
    public AggregatorType createAggregatorType() {
        return new AggregatorType();
    }

    /**
     * Create an instance of {@link PublisherType }
     * 
     */
    public PublisherType createPublisherType() {
        return new PublisherType();
    }

    /**
     * Create an instance of {@link Feed.Reviews }
     * 
     */
    public Feed.Reviews createFeedReviews() {
        return new Feed.Reviews();
    }

    /**
     * Create an instance of {@link Feed.DeletedReviews }
     * 
     */
    public Feed.DeletedReviews createFeedDeletedReviews() {
        return new Feed.DeletedReviews();
    }

    /**
     * Create an instance of {@link ReviewUrlType }
     * 
     */
    public ReviewUrlType createReviewUrlType() {
        return new ReviewUrlType();
    }

    /**
     * Create an instance of {@link MpnsType }
     * 
     */
    public MpnsType createMpnsType() {
        return new MpnsType();
    }

    /**
     * Create an instance of {@link GtinsType }
     * 
     */
    public GtinsType createGtinsType() {
        return new GtinsType();
    }

    /**
     * Create an instance of {@link ReviewerNameType }
     * 
     */
    public ReviewerNameType createReviewerNameType() {
        return new ReviewerNameType();
    }

    /**
     * Create an instance of {@link ReviewImageType }
     * 
     */
    public ReviewImageType createReviewImageType() {
        return new ReviewImageType();
    }

    /**
     * Create an instance of {@link BrandsType }
     * 
     */
    public BrandsType createBrandsType() {
        return new BrandsType();
    }

    /**
     * Create an instance of {@link SkusType }
     * 
     */
    public SkusType createSkusType() {
        return new SkusType();
    }

    /**
     * Create an instance of {@link RatingType }
     * 
     */
    public RatingType createRatingType() {
        return new RatingType();
    }

    /**
     * Create an instance of {@link ProductIdsType }
     * 
     */
    public ProductIdsType createProductIdsType() {
        return new ProductIdsType();
    }

    /**
     * Create an instance of {@link ReviewerType }
     * 
     */
    public ReviewerType createReviewerType() {
        return new ReviewerType();
    }

    /**
     * Create an instance of {@link ProductType }
     * 
     */
    public ProductType createProductType() {
        return new ProductType();
    }

    /**
     * Create an instance of {@link ReviewType.Pros }
     * 
     */
    public ReviewType.Pros createReviewTypePros() {
        return new ReviewType.Pros();
    }

    /**
     * Create an instance of {@link ReviewType.Cons }
     * 
     */
    public ReviewType.Cons createReviewTypeCons() {
        return new ReviewType.Cons();
    }

    /**
     * Create an instance of {@link ReviewType.ReviewerImages }
     * 
     */
    public ReviewType.ReviewerImages createReviewTypeReviewerImages() {
        return new ReviewType.ReviewerImages();
    }

    /**
     * Create an instance of {@link ReviewType.Ratings }
     * 
     */
    public ReviewType.Ratings createReviewTypeRatings() {
        return new ReviewType.Ratings();
    }

    /**
     * Create an instance of {@link ReviewType.Products }
     * 
     */
    public ReviewType.Products createReviewTypeProducts() {
        return new ReviewType.Products();
    }

}
