//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:24:40 AM IST 
//


package com.example.review.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The product identifier entity.
 *             
 * 
 * <p>Java class for productIdsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="productIdsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gtins" type="{}gtinsType" minOccurs="0"/>
 *         &lt;element name="mpns" type="{}mpnsType" minOccurs="0"/>
 *         &lt;element name="skus" type="{}skusType" minOccurs="0"/>
 *         &lt;element name="brands" type="{}brandsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "productIdsType", propOrder = {
    "gtins",
    "mpns",
    "skus",
    "brands"
})
public class ProductIdsType {

    protected GtinsType gtins;
    protected MpnsType mpns;
    protected SkusType skus;
    protected BrandsType brands;

    /**
     * Gets the value of the gtins property.
     * 
     * @return
     *     possible object is
     *     {@link GtinsType }
     *     
     */
    public GtinsType getGtins() {
        return gtins;
    }

    /**
     * Sets the value of the gtins property.
     * 
     * @param value
     *     allowed object is
     *     {@link GtinsType }
     *     
     */
    public void setGtins(GtinsType value) {
        this.gtins = value;
    }

    /**
     * Gets the value of the mpns property.
     * 
     * @return
     *     possible object is
     *     {@link MpnsType }
     *     
     */
    public MpnsType getMpns() {
        return mpns;
    }

    /**
     * Sets the value of the mpns property.
     * 
     * @param value
     *     allowed object is
     *     {@link MpnsType }
     *     
     */
    public void setMpns(MpnsType value) {
        this.mpns = value;
    }

    /**
     * Gets the value of the skus property.
     * 
     * @return
     *     possible object is
     *     {@link SkusType }
     *     
     */
    public SkusType getSkus() {
        return skus;
    }

    /**
     * Sets the value of the skus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SkusType }
     *     
     */
    public void setSkus(SkusType value) {
        this.skus = value;
    }

    /**
     * Gets the value of the brands property.
     * 
     * @return
     *     possible object is
     *     {@link BrandsType }
     *     
     */
    public BrandsType getBrands() {
        return brands;
    }

    /**
     * Sets the value of the brands property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandsType }
     *     
     */
    public void setBrands(BrandsType value) {
        this.brands = value;
    }

}
