//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.10 at 11:24:40 AM IST 
//


package com.example.review.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *                 The review entity.
 *             
 * 
 * <p>Java class for reviewType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reviewType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="review_id" type="{}nonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="reviewer" type="{}reviewerType"/>
 *         &lt;element name="review_timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="title" type="{}nonEmptyStringType" minOccurs="0"/>
 *         &lt;element name="content" type="{}nonEmptyStringType"/>
 *         &lt;element name="pros" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="pro" type="{}nonEmptyStringType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="cons" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="con" type="{}nonEmptyStringType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="review_url" type="{}reviewUrlType"/>
 *         &lt;element name="reviewer_images" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="reviewer_image" type="{}reviewImageType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ratings">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="overall" type="{}ratingType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="products">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="product" type="{}productType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="is_spam" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="collection_method" type="{}collectionMethodType" minOccurs="0"/>
 *         &lt;element name="transaction_id" type="{}nonEmptyStringType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reviewType", propOrder = {
    "reviewId",
    "reviewer",
    "reviewTimestamp",
    "title",
    "content",
    "pros",
    "cons",
    "reviewUrl",
    "reviewerImages",
    "ratings",
    "products",
    "isSpam",
    "collectionMethod",
    "transactionId"
})
public class ReviewType {

    @XmlElement(name = "review_id")
    protected String reviewId;
    @XmlElement(required = true)
    protected ReviewerType reviewer;
    @XmlElement(name = "review_timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar reviewTimestamp;
    protected String title;
    @XmlElement(required = true)
    protected String content;
    protected ReviewType.Pros pros;
    protected ReviewType.Cons cons;
    @XmlElement(name = "review_url", required = true)
    protected ReviewUrlType reviewUrl;
    @XmlElement(name = "reviewer_images")
    protected ReviewType.ReviewerImages reviewerImages;
    @XmlElement(required = true)
    protected ReviewType.Ratings ratings;
    @XmlElement(required = true)
    protected ReviewType.Products products;
    @XmlElement(name = "is_spam")
    protected Boolean isSpam;
    @XmlElement(name = "collection_method")
    @XmlSchemaType(name = "string")
    protected CollectionMethodType collectionMethod;
    @XmlElement(name = "transaction_id")
    protected String transactionId;

    /**
     * Gets the value of the reviewId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReviewId() {
        return reviewId;
    }

    /**
     * Sets the value of the reviewId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReviewId(String value) {
        this.reviewId = value;
    }

    /**
     * Gets the value of the reviewer property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewerType }
     *     
     */
    public ReviewerType getReviewer() {
        return reviewer;
    }

    /**
     * Sets the value of the reviewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewerType }
     *     
     */
    public void setReviewer(ReviewerType value) {
        this.reviewer = value;
    }

    /**
     * Gets the value of the reviewTimestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getReviewTimestamp() {
        return reviewTimestamp;
    }

    /**
     * Sets the value of the reviewTimestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setReviewTimestamp(XMLGregorianCalendar value) {
        this.reviewTimestamp = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the pros property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType.Pros }
     *     
     */
    public ReviewType.Pros getPros() {
        return pros;
    }

    /**
     * Sets the value of the pros property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType.Pros }
     *     
     */
    public void setPros(ReviewType.Pros value) {
        this.pros = value;
    }

    /**
     * Gets the value of the cons property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType.Cons }
     *     
     */
    public ReviewType.Cons getCons() {
        return cons;
    }

    /**
     * Sets the value of the cons property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType.Cons }
     *     
     */
    public void setCons(ReviewType.Cons value) {
        this.cons = value;
    }

    /**
     * Gets the value of the reviewUrl property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewUrlType }
     *     
     */
    public ReviewUrlType getReviewUrl() {
        return reviewUrl;
    }

    /**
     * Sets the value of the reviewUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewUrlType }
     *     
     */
    public void setReviewUrl(ReviewUrlType value) {
        this.reviewUrl = value;
    }

    /**
     * Gets the value of the reviewerImages property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType.ReviewerImages }
     *     
     */
    public ReviewType.ReviewerImages getReviewerImages() {
        return reviewerImages;
    }

    /**
     * Sets the value of the reviewerImages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType.ReviewerImages }
     *     
     */
    public void setReviewerImages(ReviewType.ReviewerImages value) {
        this.reviewerImages = value;
    }

    /**
     * Gets the value of the ratings property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType.Ratings }
     *     
     */
    public ReviewType.Ratings getRatings() {
        return ratings;
    }

    /**
     * Sets the value of the ratings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType.Ratings }
     *     
     */
    public void setRatings(ReviewType.Ratings value) {
        this.ratings = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType.Products }
     *     
     */
    public ReviewType.Products getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType.Products }
     *     
     */
    public void setProducts(ReviewType.Products value) {
        this.products = value;
    }

    /**
     * Gets the value of the isSpam property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSpam() {
        return isSpam;
    }

    /**
     * Sets the value of the isSpam property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSpam(Boolean value) {
        this.isSpam = value;
    }

    /**
     * Gets the value of the collectionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionMethodType }
     *     
     */
    public CollectionMethodType getCollectionMethod() {
        return collectionMethod;
    }

    /**
     * Sets the value of the collectionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionMethodType }
     *     
     */
    public void setCollectionMethod(CollectionMethodType value) {
        this.collectionMethod = value;
    }

    /**
     * Gets the value of the transactionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Sets the value of the transactionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionId(String value) {
        this.transactionId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="con" type="{}nonEmptyStringType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "con"
    })
    public static class Cons {

        @XmlElement(required = true)
        protected List<String> con;

        /**
         * Gets the value of the con property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the con property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCon().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getCon() {
            if (con == null) {
                con = new ArrayList<String>();
            }
            return this.con;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="product" type="{}productType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "product"
    })
    public static class Products {

        @XmlElement(required = true)
        protected List<ProductType> product;

        /**
         * Gets the value of the product property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the product property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProduct().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProductType }
         * 
         * 
         */
        public List<ProductType> getProduct() {
            if (product == null) {
                product = new ArrayList<ProductType>();
            }
            return this.product;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="pro" type="{}nonEmptyStringType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "pro"
    })
    public static class Pros {

        @XmlElement(required = true)
        protected List<String> pro;

        /**
         * Gets the value of the pro property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the pro property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getPro().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getPro() {
            if (pro == null) {
                pro = new ArrayList<String>();
            }
            return this.pro;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="overall" type="{}ratingType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "overall"
    })
    public static class Ratings {

        @XmlElement(required = true)
        protected RatingType overall;

        /**
         * Gets the value of the overall property.
         * 
         * @return
         *     possible object is
         *     {@link RatingType }
         *     
         */
        public RatingType getOverall() {
            return overall;
        }

        /**
         * Sets the value of the overall property.
         * 
         * @param value
         *     allowed object is
         *     {@link RatingType }
         *     
         */
        public void setOverall(RatingType value) {
            this.overall = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="reviewer_image" type="{}reviewImageType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "reviewerImage"
    })
    public static class ReviewerImages {

        @XmlElement(name = "reviewer_image", required = true)
        protected List<ReviewImageType> reviewerImage;

        /**
         * Gets the value of the reviewerImage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the reviewerImage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getReviewerImage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ReviewImageType }
         * 
         * 
         */
        public List<ReviewImageType> getReviewerImage() {
            if (reviewerImage == null) {
                reviewerImage = new ArrayList<ReviewImageType>();
            }
            return this.reviewerImage;
        }

    }

}
